# Generated by Django 4.1.1 on 2022-09-20 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hackathon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamname', models.CharField(max_length=100)),
                ('collegename', models.CharField(choices=[('ABESEC', 'ABES EC'), ('ABESIT', 'ABES IT'), ('KIET', 'KIET'), ('AKGEC', 'AKG EC')], max_length=100)),
                ('domain', models.CharField(choices=[('EDUCATION', 'EDUCATION'), ('SOCIAL MEDIA', 'SOCIAL MEDIA'), ('HEALTHCARE', 'HEALTHCARE'), ('TECHNOLOGY', 'TECHNOLOGY')], max_length=50)),
                ('leadername', models.CharField(max_length=100)),
                ('leaderemail', models.EmailField(max_length=254)),
                ('leadernumber', models.CharField(max_length=10)),
                ('leadergender', models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE')], max_length=10)),
                ('branch', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=10)),
                ('member2name', models.CharField(max_length=100)),
                ('member2gender', models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE')], max_length=10)),
                ('member3name', models.CharField(max_length=100)),
                ('member3gender', models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE')], max_length=10)),
                ('member4name', models.CharField(max_length=100)),
                ('member4gender', models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE')], max_length=10)),
                ('member5name', models.CharField(max_length=100)),
                ('member5gender', models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE')], max_length=10)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
