# Generated by Django 4.1 on 2022-09-21 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathon',
            name='amount',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='transactionid',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
